### ISSUE TITLE
Optimizing over scalar inside constraints?

### ISSUE THREAD

**Issue by Kiguli** [yuanchenyang/SumOfSquares.py#10]
Hello,

I am using your tool and I am struggling to combine polynomials and scalars together in both constraints and for the optimization. I was wondering if you could provide some assistance?

Assume some semi-pseudocode as follows:

```
v1,v2 = sp.symbols('v1 v2')
V = poly_variable('V', [v1,v2], 2)
a = picos.RealVariable("a")
//or could create as
a = poly_variable('a', [v1,v2], 0)

prob = SOSProblem()
prob.add_sos_constraint(a, [v1,v2]) // a greater than zero
prob.add_sos_constraint(V-a + W, [v1,v2]) // assume W is another poly_variable
prob.set_objective('min', prob.sym_to_var(a))
prob.solve()
```

I get various different errors as I've been trying to set this up such as the assert that `deg%2==0` is false, or something to do with Primal is also an error. Some errors occur in trying to include the picos.RealVariable in the sos_constraint (I can get around this by setting the scalar as the poly_variable itself), others involve the setting objective part.

I think it particularly relates to me trying to include the positive real value inside the constraints and the optimize over the scalar. I have several constraints and several scalars so I would ideally like to maximize over scalar a - scalar b.

Any help you can provide, I would be very grateful :)

**Comment by yuanchenyang** [comment]
I think the issue here is that the input to `add_sos_constraint` should be a sympy expression, and any scalar variables should be a sympy symbol. When you want to add a constraint or refer to such a scalar variable in the objective, you need to use `prob.sym_to_var` to convert the sympy symbol to a the corresponding picos variable. 

Here's an updated example:

```python
v1, v2, a = sp.symbols('v1 v2 a')
p = poly_variable('p', [v1, v2], 2)
prob = SOSProblem()
av = prob.sym_to_var(a) # av is the picos variable corresponding to symbol `a`
prob.add_constraint(av >= 0) # Use av when referring to `a` in picos constraints/objectives
prob.add_sos_constraint(p-a, [v1, v2]) # input to add_sos_constraint should be symbolic sympy expression!
prob.set_objective('min', av) 
prob.solve()
```

Let me know if you have any other questions!

**Comment by Kiguli** [comment]
Thanks for this, I would say in general I have now got the parts working that I wanted to get working. I think it was particularly related to the sympy value needed in `add_sos_constraint` but then the picos variables needed in other parts.

I noticed a couple issues I was wondering if you knew the reasoning behind:

When I run an optimization with several constraints and maximize over say `a - (b + c*d)` where `d` is constant. Using Mosek I sometimes get a feasible solution, sometimes it violates a constraint e.g. `c` is less than zero despite a constraint that should prevent that, or the solution throws an error its infeasible. This is with the same setup for each of those runs. 

Is there a variable that I can use to check the feasibility of the solution without checking the results each time?

As a second question, does the toolbox enable multi-objective optimization? I tried simply using two commands of the optimization but it threw an error. Is there another way to do that? E.g. max `a` and min `b+c*d`?

Thanks

**Comment by yuanchenyang** [comment]
How much is the constraint violated? If it's by an amount comparable to the machine precision it's probably due to the optimization algorithm the Mosek uses not guaranteeing strictly feasible solutions. Otherwise if you can provide a working example I can try to debug. 

Picos doesn't support multi-objective optimization, so you have to implement your own multi-objective algorithms (i.e. finding a Pareto-optimal solution or the Pareto frontier) by repeatedly calling the solver with a single objective. Otherwise, I believe JuMP supports multiobjective optimization as well as sum of squares.

**Comment by Kiguli** [comment]
Thanks, that's helpful. I'll take a look at JuMP as you suggest :)
